name: Release Workflow

on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile
      run: sbt assembly
    - name: Debug (find target/)
      run: find target/
    - name: Move package to artifact dir
      run: echo -n "$GITHUB_REF" | tail -c 6 | xargs -I {} mv scala-2.13/Scala-GnuPG Webserver-assembly-{}.jar target/artifact.jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact-server-$GITHUB_REF.jar
        path: target/artifact.jar